
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorSintactico.Ascendente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Multiplicacion = 321;
  public static final int SQLCODE = 244;
  public static final int DECLARE = 44;
  public static final int INTEGER = 242;
  public static final int SIZE = 234;
  public static final int DATABASE = 41;
  public static final int RELATIVE = 212;
  public static final int SOME = 154;
  public static final int MONTH = 279;
  public static final int BOTH = 216;
  public static final int GO = 213;
  public static final int PIVOT = 119;
  public static final int CLOSE = 21;
  public static final int Coma = 338;
  public static final int PAD = 189;
  public static final int USE = 174;
  public static final int MODULE = 277;
  public static final int DAY = 276;
  public static final int CONSTRAINT = 28;
  public static final int WRITETEXT = 185;
  public static final int BROWSE = 14;
  public static final int CONTINUE = 31;
  public static final int PROCEDURE = 125;
  public static final int OPENDATASOURCE = 110;
  public static final int WRITE = 308;
  public static final int LEVEL = 262;
  public static final int FETCH = 65;
  public static final int ZONE = 311;
  public static final int CATALOG = 225;
  public static final int INTERSECT = 88;
  public static final int DENY = 47;
  public static final int OFF = 106;
  public static final int DEALLOCATE = 43;
  public static final int SECTION = 224;
  public static final int FROM = 72;
  public static final int TEXTSIZE = 159;
  public static final int DUMP = 54;
  public static final int SET = 151;
  public static final int LlaveAbrir = 344;
  public static final int ASC = 8;
  public static final int StringNoCerrado = 317;
  public static final int SQLERROR = 246;
  public static final int DIAGNOSTICS = 298;
  public static final int KEY = 92;
  public static final int TIMEZONE_HOUR = 264;
  public static final int SQLCA = 243;
  public static final int MenorIgual = 324;
  public static final int RESTRICT = 134;
  public static final int FREETEXT = 70;
  public static final int GET = 210;
  public static final int OPTION = 113;
  public static final int NUMERIC = 299;
  public static final int ARE = 201;
  public static final int LINENO = 96;
  public static final int DESCRIPTOR = 297;
  public static final int SECURITYAUDIT = 145;
  public static final int NULLIF = 104;
  public static final int POSITION = 194;
  public static final int SECOND = 222;
  public static final int DECIMAL = 283;
  public static final int COUNT = 259;
  public static final int PRECISION = 121;
  public static final int NONE = 293;
  public static final int LAST = 257;
  public static final int DISCONNECT = 301;
  public static final int CURRENT_USER = 39;
  public static final int EXECUTE = 61;
  public static final int SAVE = 143;
  public static final int TRUNCATE = 166;
  public static final int DEFAULT = 45;
  public static final int SESSION_USER = 150;
  public static final int BY = 16;
  public static final int DEFERRED = 290;
  public static final int EXISTS = 62;
  public static final int DobleNumeral = 347;
  public static final int BIT = 214;
  public static final int HAVING = 78;
  public static final int LANGUAGE = 255;
  public static final int IDENTITY_INSERT = 81;
  public static final int CURRENT_TIME = 37;
  public static final int INDEX = 85;
  public static final int THEN = 160;
  public static final int BIT_LENGTH = 215;
  public static final int AT = 207;
  public static final int EOF = 0;
  public static final int ALLOCATE = 195;
  public static final int AS = 7;
  public static final int EXTRACT = 193;
  public static final int TRIGGER = 165;
  public static final int INT = 239;
  public static final int TIMEZONE_MINUTE = 266;
  public static final int BACKUP = 10;
  public static final int VALUES = 176;
  public static final int Menos = 320;
  public static final int Menor = 331;
  public static final int NEXT = 288;
  public static final int ANY = 6;
  public static final int Parentesis = 327;
  public static final int KILL = 93;
  public static final int SUBSTRING = 252;
  public static final int PUBLIC = 126;
  public static final int SEMANTICSIMILARITYDETAILSTABLE = 148;
  public static final int CASCADED = 219;
  public static final int BREAK = 13;
  public static final int PREPARE = 197;
  public static final int END = 56;
  public static final int ELSE = 55;
  public static final int VIEW = 178;
  public static final int PERCENT = 118;
  public static final int AND = 5;
  public static final int NCHAR = 286;
  public static final int CorcheteAbrir = 340;
  public static final int RETURN = 135;
  public static final int DBCC = 42;
  public static final int CONTAINS = 29;
  public static final int ROLLBACK = 139;
  public static final int CONNECTION = 249;
  public static final int FOREIGN = 69;
  public static final int ESCAPE = 58;
  public static final int VERDADERO = 280;
  public static final int CURSOR = 40;
  public static final int Numeral = 348;
  public static final int NATURAL = 284;
  public static final int LlaveCerrar = 345;
  public static final int UNPIVOT = 171;
  public static final int IMMEDIATE = 221;
  public static final int RULE = 142;
  public static final int INTO = 89;
  public static final int ALL = 3;
  public static final int Llaves = 326;
  public static final int LOAD = 97;
  public static final int TABLESAMPLE = 158;
  public static final int COLUMN = 25;
  public static final int CorcheteCerrar = 341;
  public static final int BEGIN = 11;
  public static final int CORRESPONDING = 256;
  public static final int OPENQUERY = 111;
  public static final int OFFSETS = 107;
  public static final int LOWER = 267;
  public static final int SQLWARNING = 250;
  public static final int OCTET_LENGTH = 302;
  public static final int Punto = 339;
  public static final int UNIQUE = 170;
  public static final int GRANT = 76;
  public static final int TRY_CONVERT = 167;
  public static final int ROWS = 217;
  public static final int INTERVAL = 245;
  public static final int OPEN = 109;
  public static final int WORK = 306;
  public static final int CURRENT_DATE = 36;
  public static final int Mas = 319;
  public static final int TIMESTAMP = 263;
  public static final int ALTER = 4;
  public static final int PRIVILEGES = 203;
  public static final int TOP = 162;
  public static final int REVOKE = 137;
  public static final int FULL = 73;
  public static final int RESTORE = 133;
  public static final int EXTERNAL = 64;
  public static final int SUM = 254;
  public static final int MIN = 271;
  public static final int DatoEntero = 313;
  public static final int TEMPORARY = 258;
  public static final int ABSOLUTE = 186;
  public static final int CONVERT = 32;
  public static final int ORDER = 115;
  public static final int Modulo = 323;
  public static final int COMPUTE = 27;
  public static final int TO = 161;
  public static final int LIKE = 95;
  public static final int FILE = 66;
  public static final int ParentesisAbrir = 342;
  public static final int REPLICATION = 132;
  public static final int Identificador = 318;
  public static final int PRIMARY = 122;
  public static final int MayorIgual = 328;
  public static final int DEFERRABLE = 287;
  public static final int FLOAT = 200;
  public static final int DOUBLE = 52;
  public static final int SEMANTICKEYPHRASETABLE = 147;
  public static final int SELECT = 146;
  public static final int VARYING = 177;
  public static final int CHECK = 19;
  public static final int FIRST = 198;
  public static final int TRIM = 278;
  public static final int NAMES = 282;
  public static final int PuntoComa = 337;
  public static final int DatoFloat = 314;
  public static final int INPUT = 235;
  public static final int SQLSTATE = 248;
  public static final int WHERE = 181;
  public static final int UPDATE = 172;
  public static final int ParentesisCerrar = 343;
  public static final int BETWEEN = 12;
  public static final int RAISERROR = 127;
  public static final int RECONFIGURE = 130;
  public static final int IDENTITY = 80;
  public static final int GROUP = 77;
  public static final int TRANSLATION = 275;
  public static final int USING = 294;
  public static final int TSEQUAL = 168;
  public static final int PRESERVE = 199;
  public static final int USER = 175;
  public static final int DOMAIN = 303;
  public static final int Not = 336;
  public static final int SQL = 240;
  public static final int LOCAL = 265;
  public static final int TRANSLATE = 272;
  public static final int SYSTEM_USER = 156;
  public static final int VALUE = 296;
  public static final int ONLY = 304;
  public static final int EXIT = 63;
  public static final int Or = 335;
  public static final int LEADING = 260;
  public static final int TABLE = 157;
  public static final int SCHEMA = 144;
  public static final int Igual = 329;
  public static final int error = 1;
  public static final int REVERT = 136;
  public static final int WAITFOR = 179;
  public static final int FORTRAN = 204;
  public static final int STATISTICS = 155;
  public static final int NOCHECK = 100;
  public static final int TIME = 261;
  public static final int LEFT = 94;
  public static final int OR = 114;
  public static final int ASSERTION = 205;
  public static final int PROC = 124;
  public static final int WHENEVER = 305;
  public static final int ON = 108;
  public static final int CASCADE = 17;
  public static final int EXCEPTION = 312;
  public static final int CHAR = 227;
  public static final int OF = 105;
  public static final int ROWGUIDCOL = 141;
  public static final int DELETE = 46;
  public static final int UPPER = 289;
  public static final int ADD = 2;
  public static final int ADA = 190;
  public static final int COMMIT = 26;
  public static final int CLUSTERED = 22;
  public static final int ACTION = 188;
  public static final int JOIN = 91;
  public static final int WHEN = 180;
  public static final int NULL = 103;
  public static final int MINUTE = 274;
  public static final int INNER = 86;
  public static final int DISTRIBUTED = 51;
  public static final int TRAILING = 269;
  public static final int CONTAINSTABLE = 30;
  public static final int TRANSACTION = 164;
  public static final int NO = 291;
  public static final int OPENXML = 112;
  public static final int FUNCTION = 74;
  public static final int PRIOR = 202;
  public static final int SPACE = 238;
  public static final int CAST = 223;
  public static final int CHAR_LENGTH = 229;
  public static final int SHUTDOWN = 153;
  public static final int INSENSITIVE = 237;
  public static final int SCROLL = 220;
  public static final int CASE = 18;
  public static final int ERRLVL = 57;
  public static final int PLAN = 120;
  public static final int UPDATETEXT = 173;
  public static final int UNION = 169;
  public static final int DROP = 53;
  public static final int MAX = 270;
  public static final int OUTPUT = 310;
  public static final int PRINT = 123;
  public static final int INDICATOR = 230;
  public static final int FILLFACTOR = 67;
  public static final int GLOBAL = 211;
  public static final int Diferente = 333;
  public static final int PARTIAL = 191;
  public static final int COLLATION = 241;
  public static final int GOTO = 75;
  public static final int INCLUDE = 226;
  public static final int WHILE = 182;
  public static final int SEMANTICSIMILARITYTABLE = 149;
  public static final int FALSO = 196;
  public static final int CONNECT = 247;
  public static final int VARCHAR = 300;
  public static final int CURRENT_TIMESTAMP = 38;
  public static final int BULK = 15;
  public static final int INITIALLY = 232;
  public static final int Division = 322;
  public static final int SESSION = 228;
  public static final int AUTHORIZATION = 9;
  public static final int EXEC = 60;
  public static final int REFERENCES = 131;
  public static final int ENDEXEC = 307;
  public static final int Arroba = 346;
  public static final int CREATE = 33;
  public static final int INSERT = 87;
  public static final int CHECKPOINT = 20;
  public static final int REAL = 208;
  public static final int Mayor = 330;
  public static final int ISOLATION = 251;
  public static final int READ = 128;
  public static final int SMALLINT = 236;
  public static final int WITH = 183;
  public static final int CURRENT = 35;
  public static final int CHARACTER = 231;
  public static final int DATE = 273;
  public static final int TRAN = 163;
  public static final int DISK = 49;
  public static final int DESCRIBE = 295;
  public static final int HOLDLOCK = 79;
  public static final int OVER = 117;
  public static final int DatoString = 316;
  public static final int OUTER = 116;
  public static final int DESC = 48;
  public static final int DEC = 281;
  public static final int USAGE = 292;
  public static final int NOCLUSTERED = 101;
  public static final int HOUR = 218;
  public static final int FREETEXTTABLE = 71;
  public static final int IS = 90;
  public static final int ROWCOUNT = 140;
  public static final int IN = 84;
  public static final int OVERLAPS = 187;
  public static final int SETUSER = 152;
  public static final int Corchetes = 325;
  public static final int MERGE = 98;
  public static final int DISTINCT = 50;
  public static final int IF = 83;
  public static final int IgualIgual = 332;
  public static final int CONSTRAINTS = 253;
  public static final int UNKNOWN = 285;
  public static final int DatoBit = 315;
  public static final int RIGHT = 138;
  public static final int CROSS = 34;
  public static final int NOT = 102;
  public static final int YEAR = 309;
  public static final int MATCH = 268;
  public static final int PASCAL = 192;
  public static final int IDENTITYCOL = 82;
  public static final int EXCEPT = 59;
  public static final int NATIONAL = 99;
  public static final int READTEXT = 129;
  public static final int And = 334;
  public static final int CHARACTER_LENGTH = 233;
  public static final int COLLATE = 24;
  public static final int FOUND = 206;
  public static final int AVG = 209;
  public static final int WITHIN = 184;
  public static final int FOR = 68;
  public static final int COALESCE = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "ALL",
  "ALTER",
  "AND",
  "ANY",
  "AS",
  "ASC",
  "AUTHORIZATION",
  "BACKUP",
  "BEGIN",
  "BETWEEN",
  "BREAK",
  "BROWSE",
  "BULK",
  "BY",
  "CASCADE",
  "CASE",
  "CHECK",
  "CHECKPOINT",
  "CLOSE",
  "CLUSTERED",
  "COALESCE",
  "COLLATE",
  "COLUMN",
  "COMMIT",
  "COMPUTE",
  "CONSTRAINT",
  "CONTAINS",
  "CONTAINSTABLE",
  "CONTINUE",
  "CONVERT",
  "CREATE",
  "CROSS",
  "CURRENT",
  "CURRENT_DATE",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  "CURRENT_USER",
  "CURSOR",
  "DATABASE",
  "DBCC",
  "DEALLOCATE",
  "DECLARE",
  "DEFAULT",
  "DELETE",
  "DENY",
  "DESC",
  "DISK",
  "DISTINCT",
  "DISTRIBUTED",
  "DOUBLE",
  "DROP",
  "DUMP",
  "ELSE",
  "END",
  "ERRLVL",
  "ESCAPE",
  "EXCEPT",
  "EXEC",
  "EXECUTE",
  "EXISTS",
  "EXIT",
  "EXTERNAL",
  "FETCH",
  "FILE",
  "FILLFACTOR",
  "FOR",
  "FOREIGN",
  "FREETEXT",
  "FREETEXTTABLE",
  "FROM",
  "FULL",
  "FUNCTION",
  "GOTO",
  "GRANT",
  "GROUP",
  "HAVING",
  "HOLDLOCK",
  "IDENTITY",
  "IDENTITY_INSERT",
  "IDENTITYCOL",
  "IF",
  "IN",
  "INDEX",
  "INNER",
  "INSERT",
  "INTERSECT",
  "INTO",
  "IS",
  "JOIN",
  "KEY",
  "KILL",
  "LEFT",
  "LIKE",
  "LINENO",
  "LOAD",
  "MERGE",
  "NATIONAL",
  "NOCHECK",
  "NOCLUSTERED",
  "NOT",
  "NULL",
  "NULLIF",
  "OF",
  "OFF",
  "OFFSETS",
  "ON",
  "OPEN",
  "OPENDATASOURCE",
  "OPENQUERY",
  "OPENXML",
  "OPTION",
  "OR",
  "ORDER",
  "OUTER",
  "OVER",
  "PERCENT",
  "PIVOT",
  "PLAN",
  "PRECISION",
  "PRIMARY",
  "PRINT",
  "PROC",
  "PROCEDURE",
  "PUBLIC",
  "RAISERROR",
  "READ",
  "READTEXT",
  "RECONFIGURE",
  "REFERENCES",
  "REPLICATION",
  "RESTORE",
  "RESTRICT",
  "RETURN",
  "REVERT",
  "REVOKE",
  "RIGHT",
  "ROLLBACK",
  "ROWCOUNT",
  "ROWGUIDCOL",
  "RULE",
  "SAVE",
  "SCHEMA",
  "SECURITYAUDIT",
  "SELECT",
  "SEMANTICKEYPHRASETABLE",
  "SEMANTICSIMILARITYDETAILSTABLE",
  "SEMANTICSIMILARITYTABLE",
  "SESSION_USER",
  "SET",
  "SETUSER",
  "SHUTDOWN",
  "SOME",
  "STATISTICS",
  "SYSTEM_USER",
  "TABLE",
  "TABLESAMPLE",
  "TEXTSIZE",
  "THEN",
  "TO",
  "TOP",
  "TRAN",
  "TRANSACTION",
  "TRIGGER",
  "TRUNCATE",
  "TRY_CONVERT",
  "TSEQUAL",
  "UNION",
  "UNIQUE",
  "UNPIVOT",
  "UPDATE",
  "UPDATETEXT",
  "USE",
  "USER",
  "VALUES",
  "VARYING",
  "VIEW",
  "WAITFOR",
  "WHEN",
  "WHERE",
  "WHILE",
  "WITH",
  "WITHIN",
  "WRITETEXT",
  "ABSOLUTE",
  "OVERLAPS",
  "ACTION",
  "PAD",
  "ADA",
  "PARTIAL",
  "PASCAL",
  "EXTRACT",
  "POSITION",
  "ALLOCATE",
  "FALSO",
  "PREPARE",
  "FIRST",
  "PRESERVE",
  "FLOAT",
  "ARE",
  "PRIOR",
  "PRIVILEGES",
  "FORTRAN",
  "ASSERTION",
  "FOUND",
  "AT",
  "REAL",
  "AVG",
  "GET",
  "GLOBAL",
  "RELATIVE",
  "GO",
  "BIT",
  "BIT_LENGTH",
  "BOTH",
  "ROWS",
  "HOUR",
  "CASCADED",
  "SCROLL",
  "IMMEDIATE",
  "SECOND",
  "CAST",
  "SECTION",
  "CATALOG",
  "INCLUDE",
  "CHAR",
  "SESSION",
  "CHAR_LENGTH",
  "INDICATOR",
  "CHARACTER",
  "INITIALLY",
  "CHARACTER_LENGTH",
  "SIZE",
  "INPUT",
  "SMALLINT",
  "INSENSITIVE",
  "SPACE",
  "INT",
  "SQL",
  "COLLATION",
  "INTEGER",
  "SQLCA",
  "SQLCODE",
  "INTERVAL",
  "SQLERROR",
  "CONNECT",
  "SQLSTATE",
  "CONNECTION",
  "SQLWARNING",
  "ISOLATION",
  "SUBSTRING",
  "CONSTRAINTS",
  "SUM",
  "LANGUAGE",
  "CORRESPONDING",
  "LAST",
  "TEMPORARY",
  "COUNT",
  "LEADING",
  "TIME",
  "LEVEL",
  "TIMESTAMP",
  "TIMEZONE_HOUR",
  "LOCAL",
  "TIMEZONE_MINUTE",
  "LOWER",
  "MATCH",
  "TRAILING",
  "MAX",
  "MIN",
  "TRANSLATE",
  "DATE",
  "MINUTE",
  "TRANSLATION",
  "DAY",
  "MODULE",
  "TRIM",
  "MONTH",
  "VERDADERO",
  "DEC",
  "NAMES",
  "DECIMAL",
  "NATURAL",
  "UNKNOWN",
  "NCHAR",
  "DEFERRABLE",
  "NEXT",
  "UPPER",
  "DEFERRED",
  "NO",
  "USAGE",
  "NONE",
  "USING",
  "DESCRIBE",
  "VALUE",
  "DESCRIPTOR",
  "DIAGNOSTICS",
  "NUMERIC",
  "VARCHAR",
  "DISCONNECT",
  "OCTET_LENGTH",
  "DOMAIN",
  "ONLY",
  "WHENEVER",
  "WORK",
  "ENDEXEC",
  "WRITE",
  "YEAR",
  "OUTPUT",
  "ZONE",
  "EXCEPTION",
  "DatoEntero",
  "DatoFloat",
  "DatoBit",
  "DatoString",
  "StringNoCerrado",
  "Identificador",
  "Mas",
  "Menos",
  "Multiplicacion",
  "Division",
  "Modulo",
  "MenorIgual",
  "Corchetes",
  "Llaves",
  "Parentesis",
  "MayorIgual",
  "Igual",
  "Mayor",
  "Menor",
  "IgualIgual",
  "Diferente",
  "And",
  "Or",
  "Not",
  "PuntoComa",
  "Coma",
  "Punto",
  "CorcheteAbrir",
  "CorcheteCerrar",
  "ParentesisAbrir",
  "ParentesisCerrar",
  "LlaveAbrir",
  "LlaveCerrar",
  "Arroba",
  "DobleNumeral",
  "Numeral"
  };
}

