
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorSintactico.Ascendente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Multiplicacion = 323;
  public static final int SQLCODE = 245;
  public static final int QUOTED_IDENTIFIER = 516;
  public static final int DECLARE = 45;
  public static final int INTEGER = 243;
  public static final int SIZE = 235;
  public static final int ERROR_BROKER_CONVERSATIONS = 503;
  public static final int DATABASE = 42;
  public static final int TORN_PAGE_DETECTION = 496;
  public static final int RELATIVE = 213;
  public static final int AUTOGROW_ALL_FILES = 543;
  public static final int SOME = 155;
  public static final int INTERVAL_LENGTH_MINUTES = 486;
  public static final int DATE_CORRELATION_OPTIMIZATION = 457;
  public static final int MONTH = 280;
  public static final int BOTH = 217;
  public static final int GO = 214;
  public static final int PIVOT = 120;
  public static final int QUERY_STORE = 546;
  public static final int CLOSE = 21;
  public static final int NESTED_TRIGGERS = 472;
  public static final int MONTHS = 425;
  public static final int GB = 539;
  public static final int INFINITE = 422;
  public static final int STALE_QUERY_THRESHOLD_DAYS = 498;
  public static final int Coma = 340;
  public static final int PAD = 190;
  public static final int DATA_FLUSH_INTERVAL_SECONDS = 484;
  public static final int USE = 175;
  public static final int MODULE = 278;
  public static final int DAY = 277;
  public static final int SWITCH = 398;
  public static final int CONSTRAINT = 29;
  public static final int RECURSIVE_TRIGGERS = 517;
  public static final int ONLINE = 400;
  public static final int WRITETEXT = 186;
  public static final int MINUTES = 362;
  public static final int BROWSE = 14;
  public static final int CONTINUE = 32;
  public static final int PROCEDURE = 126;
  public static final int ANSI_NULLS = 508;
  public static final int OPENDATASOURCE = 111;
  public static final int WRITE = 309;
  public static final int LEVEL = 263;
  public static final int AUTO_UPDATE_STATISTICS = 447;
  public static final int DEFAULT_LANGUAGE = 381;
  public static final int FETCH = 66;
  public static final int OPERATION_MODE = 482;
  public static final int PAUSED = 438;
  public static final int ZONE = 312;
  public static final int CATALOG = 226;
  public static final int INTERSECT = 89;
  public static final int DENY = 48;
  public static final int OLD_PASSWORD = 383;
  public static final int OFF = 107;
  public static final int DEALLOCATE = 44;
  public static final int SECTION = 225;
  public static final int ALLOW_SNAPSHOT_ISOLATION = 505;
  public static final int FROM = 73;
  public static final int TEXTSIZE = 160;
  public static final int DUMP = 55;
  public static final int SET = 152;
  public static final int LlaveAbrir = 346;
  public static final int ASC = 8;
  public static final int StringNoCerrado = 319;
  public static final int SQLERROR = 247;
  public static final int DIAGNOSTICS = 299;
  public static final int KEY = 93;
  public static final int NEW_BROKER = 502;
  public static final int SPARSE = 387;
  public static final int TIMEZONE_HOUR = 265;
  public static final int SQLCA = 244;
  public static final int SERVER = 525;
  public static final int MenorIgual = 326;
  public static final int ROWSET = 386;
  public static final int RESTRICT = 135;
  public static final int CONTAINMENT = 454;
  public static final int RANDOMIZED = 388;
  public static final int FREETEXT = 71;
  public static final int GET = 211;
  public static final int SUSPEND = 458;
  public static final int MAXSIZE = 534;
  public static final int OPTION = 114;
  public static final int ALLOW_ENCRYPTED_VALUE_MODIFICATIONS = 382;
  public static final int NUMERIC = 300;
  public static final int COMPRESSION_DELAY = 410;
  public static final int CURSOR_DEFAULT = 456;
  public static final int ARE = 202;
  public static final int HADR = 477;
  public static final int LINENO = 97;
  public static final int RESTRICTED_USER = 463;
  public static final int DESCRIPTOR = 298;
  public static final int SECURITYAUDIT = 146;
  public static final int AUTO_CLOSE = 444;
  public static final int NULLIF = 105;
  public static final int POSITION = 195;
  public static final int SECOND = 223;
  public static final int DECIMAL = 284;
  public static final int COUNT = 260;
  public static final int PRECISION = 122;
  public static final int READ_WRITE = 461;
  public static final int NONE = 294;
  public static final int LAST = 258;
  public static final int DISCONNECT = 302;
  public static final int CURRENT_USER = 40;
  public static final int PASSWORD = 380;
  public static final int EXECUTE = 62;
  public static final int ACCELERATED_DATABASE_RECOVERY = 442;
  public static final int SAVE = 144;
  public static final int ALWAYS = 403;
  public static final int TRUNCATE = 167;
  public static final int PAD_INDEX = 408;
  public static final int PARTITION = 375;
  public static final int NON_TRANSACTED_ACCESS = 475;
  public static final int HONOR_BROKER_PRIORITY = 504;
  public static final int DEFAULT = 46;
  public static final int SESSION_USER = 151;
  public static final int BY = 16;
  public static final int DEFERRED = 291;
  public static final int MASKED = 397;
  public static final int EXISTS = 63;
  public static final int EXECUTION_COUNT = 493;
  public static final int DobleNumeral = 349;
  public static final int CHANGE_RETENTION = 452;
  public static final int TEMPORAL_HISTORY_RETENTION = 520;
  public static final int BIT = 215;
  public static final int HAVING = 79;
  public static final int ANSI_NULL_DEFAULT = 509;
  public static final int LANGUAGE = 256;
  public static final int IDENTITY_INSERT = 82;
  public static final int CURRENT_TIME = 38;
  public static final int INDEX = 86;
  public static final int THEN = 161;
  public static final int BIT_LENGTH = 216;
  public static final int AT = 208;
  public static final int EOF = 0;
  public static final int ALLOCATE = 196;
  public static final int AS = 7;
  public static final int CUSTOM = 521;
  public static final int EXTRACT = 194;
  public static final int TRIGGER = 166;
  public static final int CLEAR = 481;
  public static final int DB_CHAINING = 469;
  public static final int INT = 240;
  public static final int TIMEZONE_MINUTE = 267;
  public static final int BACKUP = 10;
  public static final int VALUES = 177;
  public static final int Menos = 322;
  public static final int Menor = 333;
  public static final int ENABLE = 399;
  public static final int NEXT = 289;
  public static final int ANY = 6;
  public static final int DETERMINISTIC = 389;
  public static final int Parentesis = 329;
  public static final int KILL = 94;
  public static final int SUBSTRING = 253;
  public static final int PUBLIC = 127;
  public static final int SEMANTICSIMILARITYDETAILSTABLE = 149;
  public static final int NEWNAME = 532;
  public static final int CASCADED = 220;
  public static final int LOGIN = 379;
  public static final int BREAK = 13;
  public static final int PREPARE = 198;
  public static final int END = 57;
  public static final int MODIFY = 441;
  public static final int ELSE = 56;
  public static final int VIEW = 179;
  public static final int SIMPLE = 480;
  public static final int PERCENT = 119;
  public static final int CHANGE_TRACKING = 415;
  public static final int AND = 5;
  public static final int NCHAR = 287;
  public static final int FILESTREAM = 392;
  public static final int PAGE = 412;
  public static final int CorcheteAbrir = 342;
  public static final int RETURN = 136;
  public static final int DBCC = 43;
  public static final int CONTAINS = 30;
  public static final int PERSISTENT_VERSION_STORE_FILEGROUP = 443;
  public static final int STATISTICS_NORECOMPUTE = 369;
  public static final int ROLLBACK = 140;
  public static final int CONNECTION = 250;
  public static final int FOREIGN = 70;
  public static final int AUTO = 429;
  public static final int ALLOW_PAGE_LOCKS = 366;
  public static final int ESCAPE = 59;
  public static final int BLOCKERS = 385;
  public static final int VERDADERO = 281;
  public static final int CURSOR = 41;
  public static final int TARGET_RECOVERY_TIME = 518;
  public static final int Numeral = 350;
  public static final int NATURAL = 285;
  public static final int HISTORY_RETENTION_PERIOD = 421;
  public static final int LlaveCerrar = 347;
  public static final int UNPIVOT = 172;
  public static final int MAXDOP = 358;
  public static final int WEEKS = 424;
  public static final int FILEGROWTH = 535;
  public static final int NONCLUSTERED = 23;
  public static final int DEFAULT_SCHEMA = 378;
  public static final int RESUME = 353;
  public static final int IMMEDIATE = 222;
  public static final int RULE = 143;
  public static final int INTO = 90;
  public static final int READONLY = 544;
  public static final int ALL = 3;
  public static final int Llaves = 328;
  public static final int LOAD = 98;
  public static final int COLUMNSTORE = 413;
  public static final int TABLESAMPLE = 159;
  public static final int COLUMN = 26;
  public static final int CorcheteCerrar = 343;
  public static final int GENERATED = 402;
  public static final int MAX_DURATION = 356;
  public static final int BEGIN = 11;
  public static final int CORRESPONDING = 257;
  public static final int OPENQUERY = 112;
  public static final int AUTOGROW_SINGLE_FILE = 542;
  public static final int OFFSETS = 108;
  public static final int FILENAME = 533;
  public static final int LOWER = 268;
  public static final int SQLWARNING = 251;
  public static final int TOTAL_EXECUTION_CPU_TIME_MS = 495;
  public static final int UNLIMITED = 536;
  public static final int OCTET_LENGTH = 303;
  public static final int AUTO_UPDATE_STATISTICS_ASYNC = 448;
  public static final int Punto = 341;
  public static final int UNIQUE = 171;
  public static final int PAGE_VERIFY = 497;
  public static final int GRANT = 77;
  public static final int TRY_CONVERT = 168;
  public static final int ROWS = 218;
  public static final int INTERVAL = 246;
  public static final int OPEN = 110;
  public static final int ALLOWED = 467;
  public static final int HISTORY_TABLE = 419;
  public static final int WORK = 307;
  public static final int HIDDEN = 396;
  public static final int MAX_PLANS_PER_QUERY = 489;
  public static final int CURRENT_DATE = 37;
  public static final int Mas = 321;
  public static final int TIMESTAMP = 264;
  public static final int ALTER = 4;
  public static final int PRIVILEGES = 204;
  public static final int DEFAULT_FULLTEXT_LANGUAGE = 471;
  public static final int ALGORITHM = 391;
  public static final int TOP = 163;
  public static final int REVOKE = 138;
  public static final int PERIOD = 406;
  public static final int FULL = 74;
  public static final int TRACK_COLUMNS_UPDATED = 416;
  public static final int FORCE_LAST_GOOD_PLAN = 450;
  public static final int AUTO_SHRINK = 446;
  public static final int RESTORE = 134;
  public static final int EXTERNAL = 65;
  public static final int SUM = 255;
  public static final int MIN = 272;
  public static final int SECONDS = 526;
  public static final int AUTO_CLEANUP = 451;
  public static final int DatoEntero = 315;
  public static final int DIRECTORY_NAME = 476;
  public static final int TRANSFORM_NOISE_WORDS = 473;
  public static final int DATA_COMPRESSION = 411;
  public static final int TEMPORARY = 259;
  public static final int ABSOLUTE = 187;
  public static final int CONVERT = 33;
  public static final int ORDER = 116;
  public static final int LOG = 529;
  public static final int RECOVERY = 522;
  public static final int Modulo = 325;
  public static final int WAIT_STATS_CAPTURE_MODE = 490;
  public static final int AUTO_CREATE_STATISTICS = 445;
  public static final int COMPUTE = 28;
  public static final int CHECKSUM = 524;
  public static final int WEEK = 427;
  public static final int AFTER = 527;
  public static final int TO = 162;
  public static final int PARAMETERIZATION = 479;
  public static final int LIKE = 96;
  public static final int FILE = 67;
  public static final int NUMERIC_ROUNDABORT = 515;
  public static final int ParentesisAbrir = 344;
  public static final int TB = 540;
  public static final int OPTIMIZE_FOR_SEQUENTIAL_KEY = 367;
  public static final int CONCAT_NULL_YIELDS_NULL = 514;
  public static final int REPLICATION = 133;
  public static final int ENCRYPTED = 390;
  public static final int ABORT_AFTER_WAIT = 384;
  public static final int Identificador = 320;
  public static final int PRIMARY = 123;
  public static final int TWO_DIGIT_YEAR_CUTOFF = 474;
  public static final int MIGRATION_STATE = 434;
  public static final int MayorIgual = 330;
  public static final int DEFERRABLE = 288;
  public static final int FLOAT = 201;
  public static final int REORGANIZE = 351;
  public static final int DOUBLE = 53;
  public static final int OFFLINE = 401;
  public static final int SEMANTICKEYPHRASETABLE = 148;
  public static final int SYSTEM_VERSIONING = 417;
  public static final int TOTAL_COMPILE_CPU_TIME_MS = 494;
  public static final int PARTITIONS = 374;
  public static final int SELECT = 147;
  public static final int VARYING = 178;
  public static final int REBUILD = 357;
  public static final int CHECK = 19;
  public static final int FIRST = 199;
  public static final int TRIM = 279;
  public static final int STALE_CAPTURE_POLICY_THRESHOLD = 492;
  public static final int LOB_COMPACTION = 363;
  public static final int DISABLE = 352;
  public static final int NAMES = 283;
  public static final int PuntoComa = 339;
  public static final int DatoFloat = 316;
  public static final int REMOVE = 530;
  public static final int INPUT = 236;
  public static final int SQLSTATE = 249;
  public static final int WHERE = 182;
  public static final int UPDATE = 173;
  public static final int SELF = 361;
  public static final int ParentesisCerrar = 345;
  public static final int BETWEEN = 12;
  public static final int CREDENTIAL = 528;
  public static final int ABORT = 355;
  public static final int DISABLED = 466;
  public static final int ANSI_WARNINGS = 511;
  public static final int RAISERROR = 128;
  public static final int RECONFIGURE = 131;
  public static final int IDENTITY = 81;
  public static final int GROUP = 78;
  public static final int CLEANUP_POLICY = 483;
  public static final int TRANSLATION = 276;
  public static final int USING = 295;
  public static final int TSEQUAL = 169;
  public static final int PRESERVE = 200;
  public static final int QUERY_CAPTURE_MODE = 488;
  public static final int USER = 176;
  public static final int DOMAIN = 304;
  public static final int ARITHABORT = 512;
  public static final int Not = 338;
  public static final int SQL = 241;
  public static final int FILETABLE_DIRECTORY = 431;
  public static final int LOCAL = 266;
  public static final int TRANSLATE = 273;
  public static final int SYSTEM_USER = 157;
  public static final int SCHEMABINDING = 372;
  public static final int VALUE = 297;
  public static final int ONLY = 305;
  public static final int READ_COMITTED_SNAPSHOT = 506;
  public static final int ENABLE_BROKER = 500;
  public static final int MIXED_PAGE_ALLOCATION = 478;
  public static final int EXIT = 64;
  public static final int Or = 337;
  public static final int FILTER_PREDICATE = 435;
  public static final int HOURS = 453;
  public static final int WAIT_AT_LOW_PRIORITY = 359;
  public static final int DAYS = 423;
  public static final int LEADING = 261;
  public static final int TABLE = 158;
  public static final int OFF_WITHOUT_DATA_RECOVERY = 433;
  public static final int SCHEMA = 145;
  public static final int Igual = 331;
  public static final int error = 1;
  public static final int REVERT = 137;
  public static final int WAITFOR = 180;
  public static final int TRUSTWORTHY = 470;
  public static final int FORTRAN = 205;
  public static final int STATISTICS = 156;
  public static final int NOCHECK = 101;
  public static final int TIME = 262;
  public static final int LEFT = 95;
  public static final int MOVE = 439;
  public static final int OR = 115;
  public static final int COMPRESS_ALL_ROW_GROUPS = 364;
  public static final int FILEGROUP = 531;
  public static final int ASSERTION = 206;
  public static final int PROC = 125;
  public static final int WHENEVER = 306;
  public static final int ON = 109;
  public static final int CASCADE = 17;
  public static final int EXCEPTION = 313;
  public static final int SYSTEM_TIME = 407;
  public static final int FILETABLE_NAMESPACE = 430;
  public static final int CHAR = 228;
  public static final int EMERGENCY = 459;
  public static final int OF = 106;
  public static final int ROWGUIDCOL = 142;
  public static final int DELETE = 47;
  public static final int UPPER = 290;
  public static final int ADD = 2;
  public static final int QUERY_CAPTURE_POLICY = 491;
  public static final int ADA = 191;
  public static final int COMMIT = 27;
  public static final int CLUSTERED = 22;
  public static final int ACTION = 189;
  public static final int JOIN = 92;
  public static final int WHEN = 181;
  public static final int NULL = 104;
  public static final int MINUTE = 275;
  public static final int INNER = 87;
  public static final int DISTRIBUTED = 52;
  public static final int TRAILING = 270;
  public static final int CONTAINSTABLE = 31;
  public static final int TRANSACTION = 165;
  public static final int NO = 292;
  public static final int OPENXML = 113;
  public static final int FUNCTION = 75;
  public static final int PRIOR = 203;
  public static final int SPACE = 239;
  public static final int CAST = 224;
  public static final int OWNER = 373;
  public static final int IGNORE_DUP_KEY = 368;
  public static final int CHAR_LENGTH = 230;
  public static final int SHUTDOWN = 154;
  public static final int START = 405;
  public static final int NAME = 377;
  public static final int INSENSITIVE = 238;
  public static final int SCROLL = 221;
  public static final int READWRITE = 545;
  public static final int COMPATIBILITY_LEVEL = 513;
  public static final int ALLOW_ROW_LOCKS = 365;
  public static final int CASE = 18;
  public static final int READ_ONLY = 460;
  public static final int ERRLVL = 58;
  public static final int PLAN = 121;
  public static final int UPDATETEXT = 174;
  public static final int UNION = 170;
  public static final int DROP = 54;
  public static final int MAX = 271;
  public static final int OUTPUT = 311;
  public static final int PRINT = 124;
  public static final int INDICATOR = 231;
  public static final int FILESTREAM_ON = 418;
  public static final int FILLFACTOR = 68;
  public static final int MB = 538;
  public static final int GLOBAL = 212;
  public static final int CURSOR_CLOSE_ON_COMMIT = 455;
  public static final int MULTI_USER = 464;
  public static final int Diferente = 335;
  public static final int PARTIAL = 192;
  public static final int FORCED = 468;
  public static final int COLLATION = 242;
  public static final int GOTO = 76;
  public static final int INCLUDE = 227;
  public static final int WHILE = 183;
  public static final int LOOK = 440;
  public static final int SEMANTICSIMILARITYTABLE = 150;
  public static final int FALSO = 197;
  public static final int CONNECT = 248;
  public static final int ENCRYPTION_TYPE = 394;
  public static final int VARCHAR = 301;
  public static final int CURRENT_TIMESTAMP = 39;
  public static final int BULK = 15;
  public static final int INITIALLY = 233;
  public static final int Division = 324;
  public static final int MAX_STORAGE_SIZE_MB = 485;
  public static final int COLUMNSTORE_ARCHIVE = 414;
  public static final int SESSION = 229;
  public static final int LOCK_ESCALATION = 428;
  public static final int AUTHORIZATION = 9;
  public static final int EXEC = 61;
  public static final int REFERENCES = 132;
  public static final int MEMORY_OPTIMIZED_DATA = 541;
  public static final int OUTBOUND = 437;
  public static final int ENDEXEC = 308;
  public static final int Arroba = 348;
  public static final int DATA_CONSISTENCY_CHECK = 420;
  public static final int CREATE = 34;
  public static final int INSERT = 88;
  public static final int CHECKPOINT = 20;
  public static final int REAL = 209;
  public static final int PAUSE = 354;
  public static final int SINGLE_USER = 462;
  public static final int Mayor = 332;
  public static final int ISOLATION = 252;
  public static final int READ = 129;
  public static final int SIZE_BASED_CLEANUP_MODE = 487;
  public static final int FEDERATED_SERVICE_ACCOUNT = 499;
  public static final int SMALLINT = 237;
  public static final int KB = 537;
  public static final int WITH = 184;
  public static final int CURRENT = 36;
  public static final int VIEW_METADATA = 376;
  public static final int CHARACTER = 232;
  public static final int DATE = 274;
  public static final int TRAN = 164;
  public static final int INCREMENTAL = 449;
  public static final int DISK = 50;
  public static final int NO_WAIT = 519;
  public static final int DESCRIBE = 296;
  public static final int MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = 507;
  public static final int ENCRYPTION = 370;
  public static final int HOLDLOCK = 80;
  public static final int OVER = 118;
  public static final int DatoString = 318;
  public static final int OUTER = 117;
  public static final int DESC = 49;
  public static final int DEC = 282;
  public static final int USAGE = 293;
  public static final int NOCLUSTERED = 102;
  public static final int HOUR = 219;
  public static final int FREETEXTTABLE = 72;
  public static final int IS = 91;
  public static final int RETURNS = 314;
  public static final int ROWCOUNT = 141;
  public static final int IN = 85;
  public static final int OVERLAPS = 188;
  public static final int ROW = 404;
  public static final int SETUSER = 153;
  public static final int Corchetes = 327;
  public static final int MERGE = 99;
  public static final int DELAYED_DURABILITY = 465;
  public static final int INBOUND = 436;
  public static final int CALLER = 360;
  public static final int DISTINCT = 51;
  public static final int IF = 84;
  public static final int IgualIgual = 334;
  public static final int CONSTRAINTS = 254;
  public static final int REMOTE_DATA_ARCHIVE = 432;
  public static final int YEARS = 426;
  public static final int BULK_LOGGED = 523;
  public static final int UNKNOWN = 286;
  public static final int DatoBit = 317;
  public static final int RIGHT = 139;
  public static final int CROSS = 35;
  public static final int NOT = 103;
  public static final int YEAR = 310;
  public static final int MATCH = 269;
  public static final int ANSI_PADDING = 510;
  public static final int PASCAL = 193;
  public static final int IDENTITYCOL = 83;
  public static final int PERSISTED = 395;
  public static final int CALLED = 371;
  public static final int EXCEPT = 60;
  public static final int NATIONAL = 100;
  public static final int DISABLE_BROKER = 501;
  public static final int COLUMN_ENCRYPTION_KEY = 393;
  public static final int READTEXT = 130;
  public static final int And = 336;
  public static final int CHARACTER_LENGTH = 234;
  public static final int COLLATE = 25;
  public static final int FOUND = 207;
  public static final int AVG = 210;
  public static final int WITHIN = 185;
  public static final int FOR = 69;
  public static final int COALESCE = 24;
  public static final int STATISTICS_INCREMENTAL = 409;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "ALL",
  "ALTER",
  "AND",
  "ANY",
  "AS",
  "ASC",
  "AUTHORIZATION",
  "BACKUP",
  "BEGIN",
  "BETWEEN",
  "BREAK",
  "BROWSE",
  "BULK",
  "BY",
  "CASCADE",
  "CASE",
  "CHECK",
  "CHECKPOINT",
  "CLOSE",
  "CLUSTERED",
  "NONCLUSTERED",
  "COALESCE",
  "COLLATE",
  "COLUMN",
  "COMMIT",
  "COMPUTE",
  "CONSTRAINT",
  "CONTAINS",
  "CONTAINSTABLE",
  "CONTINUE",
  "CONVERT",
  "CREATE",
  "CROSS",
  "CURRENT",
  "CURRENT_DATE",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  "CURRENT_USER",
  "CURSOR",
  "DATABASE",
  "DBCC",
  "DEALLOCATE",
  "DECLARE",
  "DEFAULT",
  "DELETE",
  "DENY",
  "DESC",
  "DISK",
  "DISTINCT",
  "DISTRIBUTED",
  "DOUBLE",
  "DROP",
  "DUMP",
  "ELSE",
  "END",
  "ERRLVL",
  "ESCAPE",
  "EXCEPT",
  "EXEC",
  "EXECUTE",
  "EXISTS",
  "EXIT",
  "EXTERNAL",
  "FETCH",
  "FILE",
  "FILLFACTOR",
  "FOR",
  "FOREIGN",
  "FREETEXT",
  "FREETEXTTABLE",
  "FROM",
  "FULL",
  "FUNCTION",
  "GOTO",
  "GRANT",
  "GROUP",
  "HAVING",
  "HOLDLOCK",
  "IDENTITY",
  "IDENTITY_INSERT",
  "IDENTITYCOL",
  "IF",
  "IN",
  "INDEX",
  "INNER",
  "INSERT",
  "INTERSECT",
  "INTO",
  "IS",
  "JOIN",
  "KEY",
  "KILL",
  "LEFT",
  "LIKE",
  "LINENO",
  "LOAD",
  "MERGE",
  "NATIONAL",
  "NOCHECK",
  "NOCLUSTERED",
  "NOT",
  "NULL",
  "NULLIF",
  "OF",
  "OFF",
  "OFFSETS",
  "ON",
  "OPEN",
  "OPENDATASOURCE",
  "OPENQUERY",
  "OPENXML",
  "OPTION",
  "OR",
  "ORDER",
  "OUTER",
  "OVER",
  "PERCENT",
  "PIVOT",
  "PLAN",
  "PRECISION",
  "PRIMARY",
  "PRINT",
  "PROC",
  "PROCEDURE",
  "PUBLIC",
  "RAISERROR",
  "READ",
  "READTEXT",
  "RECONFIGURE",
  "REFERENCES",
  "REPLICATION",
  "RESTORE",
  "RESTRICT",
  "RETURN",
  "REVERT",
  "REVOKE",
  "RIGHT",
  "ROLLBACK",
  "ROWCOUNT",
  "ROWGUIDCOL",
  "RULE",
  "SAVE",
  "SCHEMA",
  "SECURITYAUDIT",
  "SELECT",
  "SEMANTICKEYPHRASETABLE",
  "SEMANTICSIMILARITYDETAILSTABLE",
  "SEMANTICSIMILARITYTABLE",
  "SESSION_USER",
  "SET",
  "SETUSER",
  "SHUTDOWN",
  "SOME",
  "STATISTICS",
  "SYSTEM_USER",
  "TABLE",
  "TABLESAMPLE",
  "TEXTSIZE",
  "THEN",
  "TO",
  "TOP",
  "TRAN",
  "TRANSACTION",
  "TRIGGER",
  "TRUNCATE",
  "TRY_CONVERT",
  "TSEQUAL",
  "UNION",
  "UNIQUE",
  "UNPIVOT",
  "UPDATE",
  "UPDATETEXT",
  "USE",
  "USER",
  "VALUES",
  "VARYING",
  "VIEW",
  "WAITFOR",
  "WHEN",
  "WHERE",
  "WHILE",
  "WITH",
  "WITHIN",
  "WRITETEXT",
  "ABSOLUTE",
  "OVERLAPS",
  "ACTION",
  "PAD",
  "ADA",
  "PARTIAL",
  "PASCAL",
  "EXTRACT",
  "POSITION",
  "ALLOCATE",
  "FALSO",
  "PREPARE",
  "FIRST",
  "PRESERVE",
  "FLOAT",
  "ARE",
  "PRIOR",
  "PRIVILEGES",
  "FORTRAN",
  "ASSERTION",
  "FOUND",
  "AT",
  "REAL",
  "AVG",
  "GET",
  "GLOBAL",
  "RELATIVE",
  "GO",
  "BIT",
  "BIT_LENGTH",
  "BOTH",
  "ROWS",
  "HOUR",
  "CASCADED",
  "SCROLL",
  "IMMEDIATE",
  "SECOND",
  "CAST",
  "SECTION",
  "CATALOG",
  "INCLUDE",
  "CHAR",
  "SESSION",
  "CHAR_LENGTH",
  "INDICATOR",
  "CHARACTER",
  "INITIALLY",
  "CHARACTER_LENGTH",
  "SIZE",
  "INPUT",
  "SMALLINT",
  "INSENSITIVE",
  "SPACE",
  "INT",
  "SQL",
  "COLLATION",
  "INTEGER",
  "SQLCA",
  "SQLCODE",
  "INTERVAL",
  "SQLERROR",
  "CONNECT",
  "SQLSTATE",
  "CONNECTION",
  "SQLWARNING",
  "ISOLATION",
  "SUBSTRING",
  "CONSTRAINTS",
  "SUM",
  "LANGUAGE",
  "CORRESPONDING",
  "LAST",
  "TEMPORARY",
  "COUNT",
  "LEADING",
  "TIME",
  "LEVEL",
  "TIMESTAMP",
  "TIMEZONE_HOUR",
  "LOCAL",
  "TIMEZONE_MINUTE",
  "LOWER",
  "MATCH",
  "TRAILING",
  "MAX",
  "MIN",
  "TRANSLATE",
  "DATE",
  "MINUTE",
  "TRANSLATION",
  "DAY",
  "MODULE",
  "TRIM",
  "MONTH",
  "VERDADERO",
  "DEC",
  "NAMES",
  "DECIMAL",
  "NATURAL",
  "UNKNOWN",
  "NCHAR",
  "DEFERRABLE",
  "NEXT",
  "UPPER",
  "DEFERRED",
  "NO",
  "USAGE",
  "NONE",
  "USING",
  "DESCRIBE",
  "VALUE",
  "DESCRIPTOR",
  "DIAGNOSTICS",
  "NUMERIC",
  "VARCHAR",
  "DISCONNECT",
  "OCTET_LENGTH",
  "DOMAIN",
  "ONLY",
  "WHENEVER",
  "WORK",
  "ENDEXEC",
  "WRITE",
  "YEAR",
  "OUTPUT",
  "ZONE",
  "EXCEPTION",
  "RETURNS",
  "DatoEntero",
  "DatoFloat",
  "DatoBit",
  "DatoString",
  "StringNoCerrado",
  "Identificador",
  "Mas",
  "Menos",
  "Multiplicacion",
  "Division",
  "Modulo",
  "MenorIgual",
  "Corchetes",
  "Llaves",
  "Parentesis",
  "MayorIgual",
  "Igual",
  "Mayor",
  "Menor",
  "IgualIgual",
  "Diferente",
  "And",
  "Or",
  "Not",
  "PuntoComa",
  "Coma",
  "Punto",
  "CorcheteAbrir",
  "CorcheteCerrar",
  "ParentesisAbrir",
  "ParentesisCerrar",
  "LlaveAbrir",
  "LlaveCerrar",
  "Arroba",
  "DobleNumeral",
  "Numeral",
  "REORGANIZE",
  "DISABLE",
  "RESUME",
  "PAUSE",
  "ABORT",
  "MAX_DURATION",
  "REBUILD",
  "MAXDOP",
  "WAIT_AT_LOW_PRIORITY",
  "CALLER",
  "SELF",
  "MINUTES",
  "LOB_COMPACTION",
  "COMPRESS_ALL_ROW_GROUPS",
  "ALLOW_ROW_LOCKS",
  "ALLOW_PAGE_LOCKS",
  "OPTIMIZE_FOR_SEQUENTIAL_KEY",
  "IGNORE_DUP_KEY",
  "STATISTICS_NORECOMPUTE",
  "ENCRYPTION",
  "CALLED",
  "SCHEMABINDING",
  "OWNER",
  "PARTITIONS",
  "PARTITION",
  "VIEW_METADATA",
  "NAME",
  "DEFAULT_SCHEMA",
  "LOGIN",
  "PASSWORD",
  "DEFAULT_LANGUAGE",
  "ALLOW_ENCRYPTED_VALUE_MODIFICATIONS",
  "OLD_PASSWORD",
  "ABORT_AFTER_WAIT",
  "BLOCKERS",
  "ROWSET",
  "SPARSE",
  "RANDOMIZED",
  "DETERMINISTIC",
  "ENCRYPTED",
  "ALGORITHM",
  "FILESTREAM",
  "COLUMN_ENCRYPTION_KEY",
  "ENCRYPTION_TYPE",
  "PERSISTED",
  "HIDDEN",
  "MASKED",
  "SWITCH",
  "ENABLE",
  "ONLINE",
  "OFFLINE",
  "GENERATED",
  "ALWAYS",
  "ROW",
  "START",
  "PERIOD",
  "SYSTEM_TIME",
  "PAD_INDEX",
  "STATISTICS_INCREMENTAL",
  "COMPRESSION_DELAY",
  "DATA_COMPRESSION",
  "PAGE",
  "COLUMNSTORE",
  "COLUMNSTORE_ARCHIVE",
  "CHANGE_TRACKING",
  "TRACK_COLUMNS_UPDATED",
  "SYSTEM_VERSIONING",
  "FILESTREAM_ON",
  "HISTORY_TABLE",
  "DATA_CONSISTENCY_CHECK",
  "HISTORY_RETENTION_PERIOD",
  "INFINITE",
  "DAYS",
  "WEEKS",
  "MONTHS",
  "YEARS",
  "WEEK",
  "LOCK_ESCALATION",
  "AUTO",
  "FILETABLE_NAMESPACE",
  "FILETABLE_DIRECTORY",
  "REMOTE_DATA_ARCHIVE",
  "OFF_WITHOUT_DATA_RECOVERY",
  "MIGRATION_STATE",
  "FILTER_PREDICATE",
  "INBOUND",
  "OUTBOUND",
  "PAUSED",
  "MOVE",
  "LOOK",
  "MODIFY",
  "ACCELERATED_DATABASE_RECOVERY",
  "PERSISTENT_VERSION_STORE_FILEGROUP",
  "AUTO_CLOSE",
  "AUTO_CREATE_STATISTICS",
  "AUTO_SHRINK",
  "AUTO_UPDATE_STATISTICS",
  "AUTO_UPDATE_STATISTICS_ASYNC",
  "INCREMENTAL",
  "FORCE_LAST_GOOD_PLAN",
  "AUTO_CLEANUP",
  "CHANGE_RETENTION",
  "HOURS",
  "CONTAINMENT",
  "CURSOR_CLOSE_ON_COMMIT",
  "CURSOR_DEFAULT",
  "DATE_CORRELATION_OPTIMIZATION",
  "SUSPEND",
  "EMERGENCY",
  "READ_ONLY",
  "READ_WRITE",
  "SINGLE_USER",
  "RESTRICTED_USER",
  "MULTI_USER",
  "DELAYED_DURABILITY",
  "DISABLED",
  "ALLOWED",
  "FORCED",
  "DB_CHAINING",
  "TRUSTWORTHY",
  "DEFAULT_FULLTEXT_LANGUAGE",
  "NESTED_TRIGGERS",
  "TRANSFORM_NOISE_WORDS",
  "TWO_DIGIT_YEAR_CUTOFF",
  "NON_TRANSACTED_ACCESS",
  "DIRECTORY_NAME",
  "HADR",
  "MIXED_PAGE_ALLOCATION",
  "PARAMETERIZATION",
  "SIMPLE",
  "CLEAR",
  "OPERATION_MODE",
  "CLEANUP_POLICY",
  "DATA_FLUSH_INTERVAL_SECONDS",
  "MAX_STORAGE_SIZE_MB",
  "INTERVAL_LENGTH_MINUTES",
  "SIZE_BASED_CLEANUP_MODE",
  "QUERY_CAPTURE_MODE",
  "MAX_PLANS_PER_QUERY",
  "WAIT_STATS_CAPTURE_MODE",
  "QUERY_CAPTURE_POLICY",
  "STALE_CAPTURE_POLICY_THRESHOLD",
  "EXECUTION_COUNT",
  "TOTAL_COMPILE_CPU_TIME_MS",
  "TOTAL_EXECUTION_CPU_TIME_MS",
  "TORN_PAGE_DETECTION",
  "PAGE_VERIFY",
  "STALE_QUERY_THRESHOLD_DAYS",
  "FEDERATED_SERVICE_ACCOUNT",
  "ENABLE_BROKER",
  "DISABLE_BROKER",
  "NEW_BROKER",
  "ERROR_BROKER_CONVERSATIONS",
  "HONOR_BROKER_PRIORITY",
  "ALLOW_SNAPSHOT_ISOLATION",
  "READ_COMITTED_SNAPSHOT",
  "MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT",
  "ANSI_NULLS",
  "ANSI_NULL_DEFAULT",
  "ANSI_PADDING",
  "ANSI_WARNINGS",
  "ARITHABORT",
  "COMPATIBILITY_LEVEL",
  "CONCAT_NULL_YIELDS_NULL",
  "NUMERIC_ROUNDABORT",
  "QUOTED_IDENTIFIER",
  "RECURSIVE_TRIGGERS",
  "TARGET_RECOVERY_TIME",
  "NO_WAIT",
  "TEMPORAL_HISTORY_RETENTION",
  "CUSTOM",
  "RECOVERY",
  "BULK_LOGGED",
  "CHECKSUM",
  "SERVER",
  "SECONDS",
  "AFTER",
  "CREDENTIAL",
  "LOG",
  "REMOVE",
  "FILEGROUP",
  "NEWNAME",
  "FILENAME",
  "MAXSIZE",
  "FILEGROWTH",
  "UNLIMITED",
  "KB",
  "MB",
  "GB",
  "TB",
  "MEMORY_OPTIMIZED_DATA",
  "AUTOGROW_SINGLE_FILE",
  "AUTOGROW_ALL_FILES",
  "READONLY",
  "READWRITE",
  "QUERY_STORE"
  };
}

